### PR TITLE
SOA migration update

### PR DESCRIPTION
**Pull request by streamnsight**
# WMS ID 2560

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by klazarz — COMMENTED** [review]
@streamnsight I saw that you updated the URL to the need-help content in other workshops (other than WMS 2560).
It should point to the correct need help markdown in the common repository though: https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md

**Comment by anooshapilli** [comment]
@streamnsight - Just following up on this PR.

**Comment by streamnsight** [comment]
@anooshapilli I made the change

**Comment by anooshapilli** [comment]
@streamnsight Could you confirm if you have committed the change and pushed it to your repo? I still do not see the change.

**Review by anooshapilli — APPROVED** [review]

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
