### PR TITLE
ID#2700 - PeopleSoft Cloud Manager On OCI

### PR DESCRIPTION
**Pull request by mdeepak2021**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@mdeepak2021 - Please resolve the conflicting files to review the PR. For reference on resolving this issue, you can follow the steps in Issue 1 of troubleshooting section of the lab - https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=6-labs-publish#Appendix:TroubleshootingTips

**Comment by mdeepak2021** [comment]
Can you confirm if this is okay now?

**Review by anooshapilli — COMMENTED** [review]
@mdeepak2021 - please make these changes to further review the PR
- Number these instructions, and rename the image files to lowercase
image
- Resolve this conflict issue
image
image

- Remove the readme files from images folder
image
- This lab Task 7 has 97 steps . please breakdown into further tasks
image

**Comment by mdeepak2021** [comment]
@anooshapilli Updated the changes as suggested and removed files that were not required. Let me know if we are good now

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
